# Cholesky Factorization Method

conditions:
1- The matrix A should be symmetric
2- The matrix A should be positive definite

In [15]:
import numpy as np
from scipy.linalg import cho_solve, hilbert
from math import sqrt

In [22]:
def cholesky(A):
    n = len(A)
    # Create zero matrix for L
    L = [[0.0] * n for i in range(n)]
    for i in range(n):
        for k in range(i+1):
            tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))
            
            if (i == k): 
                L[i][k] = sqrt(A[i][i] - tmp_sum)
            else:
                L[i][k] = (1.0 / L[k][k] * (A[i][k] - tmp_sum))
    return L

# Tikhonov Regularization

In [26]:
def tikhonov(A, B, alpha):
    S = np.eye(A.shape[0]) * alpha
    A_prime = np.dot(A.T, A) + np.dot(S.T, S)
    B_prime = np.dot(A.T, B)
    return A_prime, B_prime

now we solve Ax=b where A is a Hilbert function

In [25]:
A = hilbert(6)
B = np.ones(6)
print("A:")
print(A)
print("B:")
print(B)
print("cholesky:")
print(cho_solve((np.array(cholesky(A)), True), B))

A:
[[1.         0.5        0.33333333 0.25       0.2        0.16666667]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1       ]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909]]
B:
[1. 1. 1. 1. 1. 1.]
cholesky:
[-6.000e+00  2.100e+02 -1.680e+03  5.040e+03 -6.300e+03  2.772e+03]


and then we solve it with Tikhonov Regularization when alpha is 0.000001

In [30]:
A_tikhonov, B_tikhonov = tikhonov(A, B, 0.000001)
print("Tikhonov:")
print(cho_solve((np.array(cholesky(A_tikhonov)), True), B_tikhonov))

Tikhonov:
[   4.63392384  -94.0139933   377.88832047 -313.32488742 -391.44740932
  444.18602123]
