# givens rotation QR decomposition

Let 𝐴 be an 𝑚 × 𝑛 matrix with full column rank.
The 𝑄𝑅 factorization of 𝐴 is a decomposition 𝐴 = 𝑄𝑅, where 𝑄 is an 𝑚 × 𝑚 orthogonal matrix and 𝑅 is an 𝑚 × 𝑛 upper triangular matrix.

In [1]:
import numpy as np
from math import sqrt, hypot
import scipy.linalg 

fist we implement the Givens Rotation function:

In [2]:
def givens_rotation(a, b):
    r = hypot(a, b)
    c = a/r
    s = -b/r
    return (c, s)

then we calculate the Q and R matrix

In [3]:
def givens_qr(A):
    (num_rows, num_cols) = np.shape(A)
    Q = np.identity(num_rows)
    R = np.copy(A)
    (rows, cols) = np.tril_indices(num_rows, -1, num_cols)
    for (row, col) in zip(rows, cols):
        if R[row, col] != 0:
            (c, s) = givens_rotation(R[col, col], R[row, col])
            G = np.identity(num_rows)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s
            R = np.dot(G, R)
            Q = np.dot(Q, G.T)
    return (Q, R)


here we test it:

In [4]:
A = np.array([[6, 5, 0],
              [5, 1, 4],
              [0, 4, 3]])
B = np.array([[1,1],[1,-1],[2,-1]])
(Q, R) = givens_qr(A)
print(Q)
print(R)
b=[2, 0, 0]

[[ 0.76822128  0.33265418  0.54697099]
 [ 0.6401844  -0.39918502 -0.65636519]
 [ 0.          0.854396   -0.51962244]]
[[ 7.81024968e+00  4.48129080e+00  2.56073760e+00]
 [ 2.30758718e-16  4.68166987e+00  9.66447932e-01]
 [ 3.79428043e-16  0.00000000e+00 -4.18432806e+00]]


and now we can solve Ax = b:

In [5]:
y = np.dot(Q.T,b)
xQR = np.linalg.solve(R,y) 
print(xQR)

[ 0.16993464  0.19607843 -0.26143791]
